kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-tiller-role
  namespace: default
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]