apiVersion: v1
kind: Service
metadata:
    name: service-my-laravel-app
    namespace: default
    labels:
      app: my-laravel-app
spec:
    ports:
        -   
            port: 80
            targetPort: 80
    selector:
        app: my-laravel-app
    type: NodePort
